require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StartupsController do

  def mock_startup(stubs={})
    @mock_startup ||= mock_model(Startup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all startups as @startups" do
      Startup.stub(:all) { [mock_startup] }
      get :index
      assigns(:startups).should eq([mock_startup])
    end
  end

  describe "GET show" do
    it "assigns the requested startup as @startup" do
      Startup.stub(:find).with("37") { mock_startup }
      get :show, :id => "37"
      assigns(:startup).should be(mock_startup)
    end
  end

  describe "GET new" do
    it "assigns a new startup as @startup" do
      Startup.stub(:new) { mock_startup }
      get :new
      assigns(:startup).should be(mock_startup)
    end
  end

  describe "GET edit" do
    it "assigns the requested startup as @startup" do
      Startup.stub(:find).with("37") { mock_startup }
      get :edit, :id => "37"
      assigns(:startup).should be(mock_startup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created startup as @startup" do
        Startup.stub(:new).with({'these' => 'params'}) { mock_startup(:save => true) }
        post :create, :startup => {'these' => 'params'}
        assigns(:startup).should be(mock_startup)
      end

      it "redirects to the created startup" do
        Startup.stub(:new) { mock_startup(:save => true) }
        post :create, :startup => {}
        response.should redirect_to(startup_url(mock_startup))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved startup as @startup" do
        Startup.stub(:new).with({'these' => 'params'}) { mock_startup(:save => false) }
        post :create, :startup => {'these' => 'params'}
        assigns(:startup).should be(mock_startup)
      end

      it "re-renders the 'new' template" do
        Startup.stub(:new) { mock_startup(:save => false) }
        post :create, :startup => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested startup" do
        Startup.stub(:find).with("37") { mock_startup }
        mock_startup.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :startup => {'these' => 'params'}
      end

      it "assigns the requested startup as @startup" do
        Startup.stub(:find) { mock_startup(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:startup).should be(mock_startup)
      end

      it "redirects to the startup" do
        Startup.stub(:find) { mock_startup(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(startup_url(mock_startup))
      end
    end

    describe "with invalid params" do
      it "assigns the startup as @startup" do
        Startup.stub(:find) { mock_startup(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:startup).should be(mock_startup)
      end

      it "re-renders the 'edit' template" do
        Startup.stub(:find) { mock_startup(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested startup" do
      Startup.stub(:find).with("37") { mock_startup }
      mock_startup.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the startups list" do
      Startup.stub(:find) { mock_startup }
      delete :destroy, :id => "1"
      response.should redirect_to(startups_url)
    end
  end

end
