require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StartupsController do
  fixtures :all
  render_views

  it "index action should return all objects" do
    get :index
    response.should render_template(:index)
  end

  it "show action should find user and return object" do
    get :show, :id => Startup.first
    response.should render_template(:show)
  end
   
  it "new action should render new template" do
    @controller.stubs(:current_user).returns(User.first)
    get :new
    response.should render_template(:new)
  end
   
  it "create action should render new template when model is invalid" do
    @controller.stubs(:current_user).returns(User.first)
    Startup.any_instance.stubs(:valid?).returns(false)
    post :create
    response.should render_template(:new)
  end
  
  it "create action should redirect when model is valid" do
    @controller.stubs(:current_user).returns(User.first)
    Startup.any_instance.stubs(:valid?).returns(true)
    Startup.any_instance.stubs(:id).returns(1)
    post :create
    response.should redirect_to(startup_path(1))
  end
   
  it "edit action should redirect when not logged in" do
    get :edit, :id => "ignored"
    response.should redirect_to(login_url)
  end

  it "edit action should render edit template" do
    @controller.stubs(:current_user).returns(User.first)
    get :edit, :id => Startup.first
    response.should render_template(:edit)
  end

  it "update action should redirect when not logged in" do
    put :update, :id => "ignored"
    response.should redirect_to(login_url)
  end

end
